### ISSUE TITLE
Ability to activate profile without hearing sound

### ISSUE THREAD

**Issue by cowwoc** [henrichg/PhoneProfilesPlus#41]
Everytime I activate a profile I hear some sort of a acknowledgment sound. We should be able to disable this across all profiles, even if the profile being activated has non-zero volume levels.

Also, I think there is a bug in this code because when I activate the same profile twice in a row and the profile has all-zero volume levels I still hear a sound. I expect it to be silent since the volume levels before and after are set to zero.

**Comment by henrichg** [comment]
Device and Android version?

**Comment by cowwoc** [comment]
Samsung Galaxy S9+
Android 8.0.0

**Comment by henrichg** [comment]
How is configured in profile:
- Sound profile/Ringer mode
- Volumes -> all
?

**Comment by cowwoc** [comment]
[backup.zip](https://github.com/henrichg/PhoneProfilesPlus/files/2652895/backup.zip)

See "Meeting" profile.

**Comment by cowwoc** [comment]
@henrichg Are you able to detect that the profile you are switching from/to will be in silent mode, and in such a case avoid temporarily switching the volume back on?

**Comment by henrichg** [comment]
Done. If you want, install this beta: https://drive.google.com/file/d/1M37pKkrf3y3WubjMygfZiaZsR_fFQtsr/view?usp=drivesdk

**Comment by cowwoc** [comment]
I tried the beta but the problem is still not fully solved. Moving from "Meeting" to "Meeting" avoids a sound (good!) but moving from "Meeting" to "Sleep" still gives me a sound in spite of the fact that both profiles are in silent mode.

**Comment by henrichg** [comment]
Done: https://drive.google.com/file/d/1M37pKkrf3y3WubjMygfZiaZsR_fFQtsr/view?usp=drivesdk

**Comment by cowwoc** [comment]
Looks good to me. Thank you!
